### ISSUE TITLE
Can not run additional_files with JS

### ISSUE THREAD

**Issue by station72** [judge0/judge0#409]
Hello!

I have next request

POST
http://localhost:2358/submissions/?base64_encoded=false&wait=true
`{
  "language_id": 63,
  "source_code": "const fs = require('fs'); console.log(fs.readdirSync('../').join('; ')); const myModule = require('./myModule.js'); console.log(myModule.message);",
  "additional_files": [
    {
      "name": "myModule.js",
      "content": "module.exports.message = 'Hello, world!';"
    }
  ]
}`

Response
`
{
    "stdout": "run; script.js\n",
    "time": "0.03",
    "memory": 7296,
    "stderr": "internal/modules/cjs/loader.js:800\n    throw err;\n    ^\n\nError: Cannot find module './myModule.js'\nRequire stack:\n- /box/script.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:690:27)\n    at Module.require (internal/modules/cjs/loader.js:852:19)\n    at require (internal/modules/cjs/helpers.js:74:18)\n    at Object.<anonymous> (/box/script.js:1:90)\n    at Module._compile (internal/modules/cjs/loader.js:959:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)\n    at Module.load (internal/modules/cjs/loader.js:815:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:727:14)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [ '/box/script.js' ]\n}\n",
    "token": "41a6a021-667f-446a-8fff-6a191cce8cae",
    "compile_output": null,
    "message": "Exited with error status 1",
    "status": {
        "id": 11,
        "description": "Runtime Error (NZEC)"
    }
}
`

I see only `script.js` with code from `source_code` field
But i need run some code in `myModule.js`
Can somebody explain me, where is my mistake?

**Comment by station72** [comment]
I found solution
additional_files must contain base64 zip archive with all additional files
```
{
    "source_code": "const x = require('./hello.js')",
    "language_id": 63,
    "stdin": "",
    "additional_files": "UEsDBAoAAAAAAD1VjFZsXwM8IgAAACIAAAAIAAAAaGVsbG8uanNjb25zb2xlLmxvZygnaGVsbG8gZnJvbSBoZWxsby5qcycpUEsBAj8ACgAAAAAAPVWMVmxfAzwiAAAAIgAAAAgAJAAAAAAAAAAgAAAAAAAAAGhlbGxvLmpzCgAgAAAAAAABABgAYRwxQhJt2QHx/ZdCEm3ZARBt0PkRbdkBUEsFBgAAAAABAAEAWgAAAEgAAAAAAA=="        
}
```
